name: Python Linting - Naming Conventions

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install pylint
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Run pylint
      - name: Run pylint
        run: |
          pylint --rcfile=.pylintrc python_scripts/  
